name: Python application test with Github Actions

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7]
        tox-env: ["django-111", "django-20", "django-master"]
        exclude:
          - python-version: 2.7
            tox-env: "django-20"
          - python-version: 2.7
            tox-env: "django-master"
          - python-version: 3.5
            tox-env: "django-master"
        include:
          - python-version: 3.6
            tox-env: "django-master"
            continue-on-error: true
          - python-version: 3.7
            tox-env: "django-master"
            continue-on-error: true

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt
      - name: Test with tox
        run: tox -e py${{ matrix.python-version }}-${{ matrix.tox-env }}
      - name: Report to codecov
        if: success()
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          env_vars: TOX_ENV

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment:
      name: pypi
      url: https://pypi.org/p/django-active-link
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      # retrieve your distributions here

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
